# Generated by Django 4.2.2 on 2023-11-30 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coming_id', models.IntegerField(verbose_name='coming_id')),
                ('category_id', models.IntegerField(verbose_name='category_id')),
                ('category', models.CharField(max_length=128, verbose_name='category_title')),
                ('title', models.CharField(max_length=255, verbose_name='catalog_title')),
                ('details', models.TextField(blank=True, null=True, verbose_name='catalog_details')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('unit', models.CharField(max_length=32, verbose_name='unit')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='total')),
                ('sale_quantity', models.IntegerField(verbose_name='sale_quantity')),
                ('available', models.IntegerField(verbose_name='available')),
            ],
            options={
                'db_table': 'view_catalog',
                'ordering': ['title'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewComing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datec', models.DateTimeField(verbose_name='datec')),
                ('numb', models.IntegerField(verbose_name='numb')),
                ('organization', models.CharField(max_length=256, verbose_name='organization')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='total')),
            ],
            options={
                'db_table': 'view_coming',
                'ordering': ['datec'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewOutgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateo', models.DateTimeField(verbose_name='dateo')),
                ('numb', models.IntegerField(verbose_name='numb')),
                ('consumer', models.CharField(max_length=256, verbose_name='consumer')),
                ('total', models.IntegerField(verbose_name='total')),
            ],
            options={
                'db_table': 'view_outgo',
                'ordering': ['dateo'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outgo_id', models.IntegerField(verbose_name='outgo_id')),
                ('dateo', models.DateTimeField(verbose_name='dateo')),
                ('numb', models.IntegerField(verbose_name='numb')),
                ('consumer', models.CharField(max_length=256, verbose_name='consumer')),
                ('catalog_id', models.IntegerField(verbose_name='catalog_id')),
                ('category', models.CharField(max_length=128, verbose_name='category_title')),
                ('title', models.CharField(max_length=255, verbose_name='catalog_title')),
                ('details', models.TextField(blank=True, null=True, verbose_name='catalog_details')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('unit', models.CharField(max_length=32, verbose_name='unit')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='total')),
            ],
            options={
                'db_table': 'view_sale',
                'ordering': ['outgo_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datea', models.DateTimeField(auto_now_add=True, verbose_name='datea')),
                ('title', models.CharField(max_length=255, verbose_name='application_title')),
                ('details', models.TextField(verbose_name='application_details')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='application_price')),
            ],
            options={
                'db_table': 'application',
                'ordering': ['datea'],
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='catalog_title')),
                ('details', models.TextField(blank=True, null=True, verbose_name='catalog_details')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='catalog_price')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('unit', models.CharField(max_length=32, verbose_name='unit')),
            ],
            options={
                'db_table': 'catalog',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='category_title')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='client_name')),
                ('address', models.CharField(max_length=128, verbose_name='client_address')),
                ('phone', models.CharField(max_length=32, verbose_name='client_phone')),
                ('email', models.CharField(max_length=128, verbose_name='client_email')),
                ('leader', models.CharField(max_length=128, verbose_name='client_leader')),
            ],
            options={
                'db_table': 'client',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Coming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datec', models.DateTimeField(verbose_name='datec')),
                ('numb', models.IntegerField(verbose_name='numb')),
                ('organization', models.CharField(max_length=256, verbose_name='organization')),
            ],
            options={
                'db_table': 'coming',
                'ordering': ['datec'],
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='kind_title')),
            ],
            options={
                'db_table': 'kind',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datem', models.DateTimeField(auto_now_add=True, verbose_name='datem')),
                ('details', models.TextField(blank=True, null=True, verbose_name='message_details')),
            ],
            options={
                'db_table': 'message',
                'ordering': ['-datem'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daten', models.DateTimeField(verbose_name='daten')),
                ('title', models.CharField(max_length=256, verbose_name='news_title')),
                ('details', models.TextField(verbose_name='news_details')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='news_photo')),
            ],
            options={
                'db_table': 'news',
                'ordering': ['daten'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='start')),
                ('finish', models.DateTimeField(verbose_name='finish')),
                ('title', models.CharField(max_length=256, verbose_name='notification_title')),
                ('details', models.TextField(verbose_name='notification_details')),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['start', 'finish'],
            },
        ),
        migrations.CreateModel(
            name='Outgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateo', models.DateTimeField(verbose_name='dateo')),
                ('numb', models.IntegerField(verbose_name='numb')),
                ('consumer', models.CharField(max_length=256, verbose_name='consumer')),
            ],
            options={
                'db_table': 'outgo',
                'ordering': ['dateo'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_catalog', to='small.catalog')),
                ('outgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_outgo', to='small.outgo')),
            ],
            options={
                'db_table': 'sale',
                'ordering': ['outgo'],
            },
        ),
        migrations.AddIndex(
            model_name='outgo',
            index=models.Index(fields=['dateo'], name='outgo_dateo_4b33f6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['start'], name='notificatio_start_5ed3f9_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['finish'], name='notificatio_finish_67033c_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['daten'], name='news_daten_a29edb_idx'),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_message', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_message', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='coming',
            index=models.Index(fields=['datec'], name='coming_datec_a205c8_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='client_email_1d3242_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='client_name_57da18_idx'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_category', to='small.category'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='coming',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_coming', to='small.coming'),
        ),
        migrations.AddField(
            model_name='application',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_client', to='small.client'),
        ),
        migrations.AddField(
            model_name='application',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_kind', to='small.kind'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['outgo'], name='sale_outgo_i_ce5f86_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['catalog'], name='sale_catalog_6f4233_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='message_sender__0e912c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient'], name='message_recipie_5f6840_idx'),
        ),
        migrations.AddIndex(
            model_name='catalog',
            index=models.Index(fields=['title'], name='catalog_title_a1bae3_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['datea'], name='application_datea_198fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['client'], name='application_client__4c2e5c_idx'),
        ),
    ]
